'use client';

import { createTheme, ThemeProvider } from '@mui/material';
import './global.css';
import '@mui/material-pigment-css/styles.css';


// export const metadata = {
//   title: 'Welcome to admin-portal',
//   description: 'Generated by create-nx-workspace',
// };


const theme=  createTheme({
  });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme} >
        {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
